#!/bin/bash

channel_dir=/home/mc/xdg-user-dirs/media/job/channel

function print_help() {
cat<<EOF
USAGE: ch [OPTION]
       ch -r [CHANNEL]
       -b  print bs channels 
       -c  print cs channels
       -d  print digital channels
       -r  print recording option
       -h  print help message
EOF
exit
}

file=none
while getopts 'bcdhr:' opt;do
    case $opt in
        b)
            file=${channel_dir}/bs
            ;;
        c)
            file=${channel_dir}/cs
            ;;
        d)
            file=${channel_dir}/digital
            ;;
        r)
            cat ${channel_dir}/bs ${channel_dir}/cs ${channel_dir}/digital |
            awk -v channel=$OPTARG '{ if ($1 == channel) { printf("--sid %s %s\n", $2, $1) } }'
            exit
            ;;
        h)
            print_help
            ;;
    esac
done
shift $(($OPTIND -1))

if [ "$file" = "none" ];then
    print_help
fi

awk '{ printf("%s\t%s\t%s\t%s\n", $4, $2, $1, $3) }' $file |
column -t -s '	'
