#!/bin/bash

channel_dir=/home/mc/xdg-user-dirs/media/job/channel

function print_help() {
cat<<EOF
USAGE: ch [OPTION] [CHANNEL]
       -b  print bs channels 
       -c  print cs channels
       -d  print digital channels
       -h  print help message
EOF
exit
}

file=none
while getopts 'bcdh' opt;do
    case $opt in
        b)
            file=${channel_dir}/bs
            ;;
        c)
            file=${channel_dir}/cs
            ;;
        d)
            file=${channel_dir}/digital
            ;;
        h)
            print_help
            ;;
    esac
done
shift $(($OPTIND -1))

if [ "$file" = "none" ];then
    print_help
fi

awk '{ printf("%s\t%s\t%s\t%s\n", $4, $2, $1, $3) }' $file |
column -t -s '	'
