#!/bin/bash

channel_dir=/home/mc/xdg-user-dirs/media/job/channel

function print_help() {
cat<<EOF
USAGE: ch [OPTION] [CHANNEL]
       -b  print bs channels 
       -c  print cs channels
       -d  print degital channels
       -h  print help message
EOF
exit
}

file=none
while getopts 'bcdh' opt;do
    case $opt in
        b)
            file=${channel_dir}/bs
            ;;
        c)
            file=${channel_dir}/cs
            ;;
        d)
            file=${channel_dir}/degital
            ;;
        h)
            print_help
            ;;
    esac
done
shift $(($OPTIND -1))

if [ "$file" = "none" ];then
    print_help
fi

grep_command=
if [ $# -gt 0 ];then
   grep_command=" | grep ^$1"
fi

eval sort -k 1 -n $file $grep_command
