#!/bin/bash

function print_help() {
cat<<EOF
USAGE: mymplayer [OPTION]... [FILE]
       -a             output audio stream to spdif dts,ac3
       -b SID         set subtitle id
       -d DELAY       set delay time
       -h             print help message
       -m             play dvd media
       -u AID         set audio id
       -v VOLUME      set volume
EOF
exit
}

delay=
volume=
audio="-ao pulse"
media=
sid=
aid=
tsprog=
while getopts 'ab:d:hmu:v:' opt;do
    case $opt in
        h)
            print_help
            ;;
        b)
            sid="-sid $OPTARG"
            ;;
        u)
            aid="-aid $OPTARG"
            ;;
        m)
            media=dvd:////dev/sr0
            ;;
        a)
            audio="-ao alsa:device=spdif -ac hwac3,hwdts,mp3,faad,ffflac,ffwmav2"
            ;;
        d)
            delay=" -delay $OPTARG "
            ;;
        v)
            volume=" -volume $OPTARG "
            ;;
    esac
done
shift $(($OPTIND -1))

if [ -z "$media" -a ! -f "$1" ];then
    print_help 
fi

input=$1

# mplayer 1
# -fs \
# -volstep 10 \
# -vf lavcdeint \
# -vo gl_nosw \

# --video-unscaled \

mpv \
--input-ar-delay 2000 \
--input-ar-rate 1 \
--fullscreen \
--deinterlace=yes \
--vo=vaapi \
--hwdec=vaapi \
$input
