#!/bin/bash

LANG=C vlc \
--overlay \
--vout xcb_glx \
--deinterlace=1 \
--video-filter=deinterlace \
--deinterlace-mode=blend \
--fullscreen \
--global-key-jump+long='Page Up' \
--global-key-jump+medium=Up \
--global-key-jump+short=Right \
--global-key-jump-long='Page Down' \
--global-key-jump-medium=Down \
--global-key-jump-short=Left \
--global-key-quit=Esc \
--global-key-vol-up=0 \
--global-key-vol-down=9 \
--short-jump-size  20   \
--medium-jump-size 100  \
--long-jump-size   1000 \
$@
