#!/bin/bash
prog_name=$(basename $0)

power_control=/home/mc/xdg-user-dirs/media/ubin/disk-power-control
usb_disk_id=/home/mc/xdg-user-dirs/media/job/state/usb_disk_id

count=$(find /dev -name 'usbhd*' | wc -l)
if [ $prog_name = "usb-disk-power-off" ];then

    if [ $count -ne 0 ];then
        sudo $power_control -l $usb_disk_id -z /dev/usbhd*
    else
        echo "USB disk power status is all ready off"
        exit 1
    fi

elif [ $prog_name = "usb-disk-power-on" ];then

    if [ $count -eq 0 ];then
        sudo $power_control -p $(cat $usb_disk_id)
    else
        echo "USB disk power status is all ready on"
        exit 1
    fi
fi
