#!/bin/bash

prog_name=$(basename $0)
lock_file=/tmp/usb_disk_power_lock_file
power_control=/home/mc/xdg-user-dirs/media/ubin/disk-power-control
usb_disk_id=/home/mc/xdg-user-dirs/media/job/state/usb_disk/id

function do_usb_disk_opration() {

    count=$($power_control -d | wc -l)

    if [ $prog_name = "usb-disk-power-off" -a $count -eq 0 ];then
        echo "USB disk power status is all ready off"
        return 1
    elif [ $prog_name = "usb-disk-power-on" -a $count -ne 0 ];then
        echo "USB disk power status is all ready on"
        return 1
    elif [ $prog_name = "usb-disk-mount" ];then

        mount_point_count=$(mount | grep ^/ | wc -l)
        if [ $mount_point_count -gt 6 ];then
            # 1 root
            # 2 usb_disk_array
            # 3 usb_disk_array bind
            # 4 usb_disk 1
            # 5 usb_disk 1 bind
            # 6 usb_disk 2
            echo "USB disk is all ready mounted"
            return 1
        fi
    fi

    if [ $prog_name = "usb-disk-power-off" ];then

        sudo $power_control -l $usb_disk_id -z

    elif [ $prog_name = "usb-disk-power-on" ];then

        sudo $power_control -p $(cat $usb_disk_id)

    elif [ $prog_name = "usb-disk-mount" ];then

        sudo $power_control -m $(cat $usb_disk_id)

    fi
}

####################################################################################################

lockfile-create $lock_file
lockfile-touch $lock_file &
pid_lock=$!

do_usb_disk_opration

kill -TERM $pid_lock
lockfile-remove $lock_file
